spring.application.name=codelens-backend

server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/codelens_db
spring.datasource.username=root
spring.datasource.password=Root@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenRouter API Key]
openrouter.api.key=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